### ISSUE TITLE
I get an error when I want to restart https, can you please help? 

### ISSUE THREAD

**Issue by mustafaiciren** [dappnode/DAppNodePackage-https-portal#82]
I get an error when I want to restart https, can you please help?

**Comment by alexpeterson91** [comment]
Hopefully your issue has been resolved since this was opened, but please use our issue templates when opening an Issue.  
This is something that should be asked on Discord, and even there you've not given any supporting information or context or even version of the software you had an issue with.  Please always follow Issue and PR templates when contributing on GitHub.
I'm going to close this issue now as i assume its been resolved, if not please read and fill out the following template when creating an issue.  And note the following note, this issue is something to go to discord for assistance, it wont even be looked at here without any information given.

 ```
<!--NOTE: -->
<!--- General questions should go to the discord chat instead of the issue tracker.-->

**Describe the bug**

<!--A clear and concise description of what the bug is.-->

**To Reproduce**

<!--Steps to reproduce the behavior:
1. Install version X
2. Set this configuration option
3. Do this action
4. See error-->

**Expected behavior**

<!--A clear and concise description of what you expected to happen.-->

**Screenshots**

<!--If applicable, add screenshots to help explain your problem.-->

**DAppNode version:**

<!--Print the DAppNode versions and info found in http://my.dappnode/#/support/report -->

- Package version: <!-- v0.1.14, upstream: prysm-1.0.0-beta -->
- OS: <!-- Ubuntu, Debian, DAppNode Mini, DAppNode Advance -->
- Browser <!-- If applicable: Brave, Firefox, Chrome, Safari -->

**Additional context**

<!--Add any other context about the problem here.-->

```
